services:
    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana-storage:/var/lib/grafana
      restart: always
    web:
      build: .
      environment:
        - DB_PASSWORD = ${DB_PASSWORD}
